### PR TITLE
Fix employee color tint in stress overlay

### LINKED ISSUE #52: display stress as employee mesh color tint

### PR DESCRIPTION
**Pull request by mertwole**
resolves #52

### CODE REVIEW

File: JamGame/Assets/Scripts/Employee/View.cs [hunk 1]
```diff
@@ -27,10 +26,11 @@ public void RevertOverlays()
         }
     }
 
-    [RequireComponent(typeof(MeshRenderer))]
     public partial class View : IOverlayRenderer<Overlay.Stress>
     {
+        [SerializeField]
         private MeshRenderer meshRenderer;
```
Comment (Kiuh) [inline JamGame/Assets/Scripts/Employee/View.cs:32]: Maybe better change to List of mesh renderers for multiple parts of Employee?

**Review by Kiuh — APPROVED** [review]

File: JamGame/Assets/Scripts/Employee/View.cs (hunk 1 above)
Comment (mertwole) [reply JamGame/Assets/Scripts/Employee/View.cs:32]: I think it can be implemented later, if needed
